# Generated by Django 4.1 on 2022-09-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "producttype",
                    models.CharField(
                        choices=[
                            ["fashion", "fashion"],
                            ["menfashion", "menfashion"],
                            ["menfashion", "menfashion"],
                            ["kids", "kids"],
                            ["books", "books"],
                            ["mobile", "mobile"],
                            ["computer", "computer"],
                            ["laptop", "laptop"],
                            ["sprots", "sprots"],
                            ["kitchen_items", "kitchen_items"],
                            ["health", "health"],
                            ["groceries", "groceries"],
                            ["movies/songs", "movies/songs"],
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[["male", "male"], ["female", "female"]], max_length=50
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("offer", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ["small", "small"],
                            ["mediam", "mediam"],
                            ["long", "long"],
                        ],
                        max_length=50,
                    ),
                ),
                ("desc", models.TextField()),
                ("photo", models.ImageField(upload_to="productpics")),
            ],
        ),
    ]
