# Generated by Django 4.1 on 2022-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cloth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("offer", models.IntegerField()),
                ("gender", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=50)),
                ("size", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("photo", models.ImageField(upload_to="clothpics")),
            ],
        ),
    ]
