# Generated by Django 4.1 on 2022-09-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloth",
            name="gender",
            field=models.CharField(
                choices=[["male", "male"], ["female", "female"]], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="cloth",
            name="size",
            field=models.CharField(
                choices=[["small", "small"], ["mediam", "mediam"], ["long", "long"]],
                max_length=50,
            ),
        ),
    ]
