# Generated by Django 4.1 on 2022-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[["male", "male"], ["female", "female"]], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("sslc_per", models.IntegerField()),
                ("puc_per", models.IntegerField()),
                ("mail_id", models.CharField(max_length=50)),
                ("phone_no", models.BigIntegerField()),
                ("address", models.TextField()),
            ],
        ),
    ]
