# Generated by Django 4.1 on 2022-09-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="mail_id", new_name="email_id",
        ),
    ]
